from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('literature/search/', views.literature_search, name='literature_search'),
    path('literature/link/<int:project_pk>/', views.literature_link_to_project, name='literature_link_to_project'),
    path('literature/fulltext/', views.literature_fulltext_search, name='literature_fulltext_search'),
    path('experiments/', views.experiments_list, name='experiments_list'),
    path('experiments/new/', views.experiments_create, name='experiments_create'),
    path('experiments/<int:pk>/', views.experiments_detail, name='experiments_detail'),
    path('experiments/<int:pk>/run/', views.experiments_run, name='experiments_run'),
    path('experiments/<int:pk>/run-ajax/', views.experiments_run_ajax, name='experiments_run_ajax'),
    path('experiments/<int:pk>/history/', views.experiments_run_history, name='experiments_run_history'),
    path('experiments/<int:pk>/duplicate/', views.experiments_duplicate, name='experiments_duplicate'),
    path('experiments/templates/', views.experiments_templates, name='experiments_templates'),
    path('projects/<int:project_pk>/experiments/create-ajax/', views.experiments_create_ajax, name='experiments_create_ajax'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/new/', views.projects_create, name='projects_create'),
    path('projects/<int:pk>/', views.projects_detail, name='projects_detail'),
    path('projects/<int:pk>/assistant/chat/', views.project_chat, name='project_chat'),
    path('projects/<int:pk>/paper/update/', views.projects_update_paper, name='projects_update_paper'),
    path('projects/<int:pk>/paper/recompile/', views.projects_recompile_paper, name='projects_recompile_paper'),
    path('projects/<int:pk>/notes/add/', views.projects_add_note, name='projects_add_note'),
    path('projects/<int:pk>/hypotheses/add/', views.projects_add_hypothesis, name='projects_add_hypothesis'),
    path('projects/<int:pk>/automation/status/', views.project_automation_status, name='project_automation_status'),
    path('settings/', views.settings_view, name='settings'),
    path('api/transcribe/', views.transcribe_audio, name='transcribe_audio'),
    path('search/', views.global_search, name='global_search'),
    path('projects/<int:pk>/delete/', views.projects_delete, name='projects_delete'),
    path('projects/<int:pk>/archive/', views.projects_archive, name='projects_archive'),
    path('projects/<int:pk>/paper/export/', views.projects_export_paper, name='projects_export_paper'),
    path('projects/<int:pk>/assistant/history/', views.project_chat_history, name='project_chat_history'),
    path('projects/<int:pk>/tab-data/', views.projects_tab_data, name='projects_tab_data'),
    path('projects/<int:pk>/paper/parse-sections/', views.projects_parse_sections, name='projects_parse_sections'),
    path('projects/<int:pk>/paper/sections/', views.projects_sections_json, name='projects_sections_json'),
    path('projects/<int:pk>/paper/sections/<int:section_id>/update/', views.projects_update_section, name='projects_update_section'),
    path('projects/<int:pk>/paper/sections/<int:section_id>/recompile/', views.projects_recompile_section, name='projects_recompile_section'),
    path('projects/<int:pk>/rerun-stage/', views.projects_rerun_stage, name='projects_rerun_stage'),
    path('projects/<int:pk>/rerun-full/', views.projects_rerun_full, name='projects_rerun_full'),
]